public interface ShooterConstants{
  
    int MOTOR_ID = 0; // TODO: find ID
    double PEAK_CURRENT = 0;// TODO find value 
    int MM_CRUISE = 0; //TODO find value
    int MM_ACCELERATION = 0; //TODO find value 
    int MM_JERK = 0;// TODO find value
    double KP = 0; // TODO find value
    double KD = 0;// TODO find value
    double KV = 0; //TODO find value 
    double KS = 0;//TODO find value
    double KA = 0; //TODO find value 
    int FOWORD_LIMIT = 0; //TODO find value
    int BACKWARD_LIMIT = 0; //TODO find value 
    int RESET_POSITION = 0;//TODO find value
    double TICKS_PER_DEGREE = 0 //TODO find value 
    int NEUTRAL_MODE = 0; //TODO find value
    int INVERTED = 0; //TODO find value
    








}